MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'ass4'
        PRETRAINED: True
        OUT_CHANNELS: [ 512, 1024, 2048, 256, 128, 128]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [ [38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
        STRIDES: [[7, 7], [15, 15], [30, 30], [60, 60], [100, 100], [300, 300]]
#         # Kan endres på
        ASPECT_RATIOS: [[7,5], [8], [1], [7, 5], [2], [2]]
#         # X, Y
        MIN_SIZES: [[10, 10], [30, 30], [60, 60], [162, 162], [213, 213], [264, 264]]
# #         # X, Y
        MAX_SIZES: [[30, 30], [60, 60], [162, 162], [213, 213], [264, 264], [315, 315]]
# #         # Kan ikke endres på tilfeldig, tror man bare kan ha et gitt anatall basert på antall channels eller feature maps elns
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]

INPUT:
    IMAGE_SIZE: [300, 300]
    PIXEL_MEAN: [0.485, 0.456, 0.406]
    PIXEL_STD: [0.229, 0.224, 0.225]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 15000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1.2e-3
    WEIGHT_DECAY: 3e-4
OUTPUT_DIR: 'outputs/ass4'
DATASET_DIR: "/work/datasets"
